version: "3.9"
services:
    api:
      build: .
      ports:
        - "8443:80"
      depends_on:
        - db
      environment:
        DATABASE_CONNECTIONSTRING: Server=db;Database=master;User Id=sa;Password=Resistence_Password;
    db:
      image: "mcr.microsoft.com/mssql/server"
      environment:
        SA_PASSWORD: "Resistence_Password"
        ACCEPT_EULA: "Y"
      ports:
        - 1443:1443